name: Test
on:
  push:
    branches-ignore:
      - main
  workflow_call:

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rspec:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test with RSpec
        run: bundle exec rspec --tag ~no_ci
